/* mtlc/intrinsic.h - target-neutral operations with backend-defined lowering. */
#ifndef MTLC_INTRINSIC_H
#define MTLC_INTRINSIC_H

#ifdef __cplusplus
extern "C" {
#endif

/* These are semantic IR identities, not source-level function names and not
 * PTX/SPIR-V opcodes. Backends must switch on the enum; a frontend may expose
 * any syntax or spelling it chooses. */
typedef enum {
  MTLC_INTRINSIC_NONE = 0,
  MTLC_INTRINSIC_GPU_LOCAL_ID_X,
  MTLC_INTRINSIC_GPU_LOCAL_ID_Y,
  MTLC_INTRINSIC_GPU_LOCAL_ID_Z,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_X,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_Y,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_Z,
  MTLC_INTRINSIC_GPU_GROUP_ID_X,
  MTLC_INTRINSIC_GPU_GROUP_ID_Y,
  MTLC_INTRINSIC_GPU_GROUP_ID_Z,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_X,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_Y,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_Z,
  MTLC_INTRINSIC_GPU_SUBGROUP_LOCAL_ID,
  MTLC_INTRINSIC_GPU_SUBGROUP_SIZE,
  MTLC_INTRINSIC_GPU_SUBGROUP_BROADCAST_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_BROADCAST_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MIN_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MIN_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MAX_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MAX_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_INCLUSIVE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_INCLUSIVE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_EXCLUSIVE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_EXCLUSIVE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SHUFFLE_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SHUFFLE_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_BALLOT_WORD,
  MTLC_INTRINSIC_GPU_SUBGROUP_ANY,
  MTLC_INTRINSIC_GPU_SUBGROUP_ALL,
  MTLC_INTRINSIC_GPU_WORKGROUP_BARRIER,
  MTLC_INTRINSIC_GPU_SQRT_F32,
  MTLC_INTRINSIC_GPU_RSQRT_F32,
  MTLC_INTRINSIC_GPU_ABS_F32,
  MTLC_INTRINSIC_GPU_SIN_F32,
  MTLC_INTRINSIC_GPU_COS_F32,
  MTLC_INTRINSIC_GPU_LOG_F32,
  MTLC_INTRINSIC_GPU_EXP_F32,
  MTLC_INTRINSIC_GPU_F16_BITS_TO_F32,
  MTLC_INTRINSIC_GPU_F32_TO_F16_BITS,
  MTLC_INTRINSIC_GPU_ATOMIC_MIN_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_MIN_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_ADD_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_ADD_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_SUB_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_SUB_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_MAX_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_MAX_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_AND_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_AND_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_OR_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_OR_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_XOR_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_XOR_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_EXCHANGE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_EXCHANGE_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_COMPARE_EXCHANGE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_COMPARE_EXCHANGE_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_LOAD_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_LOAD_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_STORE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_STORE_U64,
} MtlcIntrinsic;

#ifdef __cplusplus
}
#endif

#endif /* MTLC_INTRINSIC_H */
