#include "token.h"

const char *token_kind_name(TokenKind k) {
  switch (k) {
  case TK_EOF: return "end of file";
  case TK_LPAREN: return "'('";
  case TK_RPAREN: return "')'";
  case TK_LBRACE: return "'{'";
  case TK_RBRACE: return "'}'";
  case TK_LBRACKET: return "'['";
  case TK_RBRACKET: return "']'";
  case TK_SEMI: return "';'";
  case TK_COMMA: return "','";
  case TK_COLON: return "':'";
  case TK_QUESTION: return "'?'";
  case TK_DOT: return "'.'";
  case TK_ARROW: return "'->'";
  case TK_ELLIPSIS: return "'...'";
  case TK_PLUS: return "'+'";
  case TK_MINUS: return "'-'";
  case TK_STAR: return "'*'";
  case TK_SLASH: return "'/'";
  case TK_PERCENT: return "'%'";
  case TK_AMP: return "'&'";
  case TK_PIPE: return "'|'";
  case TK_CARET: return "'^'";
  case TK_TILDE: return "'~'";
  case TK_BANG: return "'!'";
  case TK_LT: return "'<'";
  case TK_GT: return "'>'";
  case TK_LE: return "'<='";
  case TK_GE: return "'>='";
  case TK_EQ: return "'=='";
  case TK_NE: return "'!='";
  case TK_LSHIFT: return "'<<'";
  case TK_RSHIFT: return "'>>'";
  case TK_ANDAND: return "'&&'";
  case TK_OROR: return "'||'";
  case TK_INC: return "'++'";
  case TK_DEC: return "'--'";
  case TK_ASSIGN: return "'='";
  case TK_ADD_ASSIGN: return "'+='";
  case TK_SUB_ASSIGN: return "'-='";
  case TK_MUL_ASSIGN: return "'*='";
  case TK_DIV_ASSIGN: return "'/='";
  case TK_MOD_ASSIGN: return "'%='";
  case TK_AND_ASSIGN: return "'&='";
  case TK_OR_ASSIGN: return "'|='";
  case TK_XOR_ASSIGN: return "'^='";
  case TK_LSHIFT_ASSIGN: return "'<<='";
  case TK_RSHIFT_ASSIGN: return "'>>='";
  case TK_IDENT: return "identifier";
  case TK_INT: return "integer literal";
  case TK_FLOAT: return "floating literal";
  case TK_CHAR: return "character literal";
  case TK_STRING: return "string literal";
  case TK_AUTO: return "'auto'";
  case TK_BREAK: return "'break'";
  case TK_CASE: return "'case'";
  case TK_CHAR_KW: return "'char'";
  case TK_CONST: return "'const'";
  case TK_CONTINUE: return "'continue'";
  case TK_DEFAULT: return "'default'";
  case TK_DO: return "'do'";
  case TK_DOUBLE: return "'double'";
  case TK_ELSE: return "'else'";
  case TK_ENUM: return "'enum'";
  case TK_EXTERN: return "'extern'";
  case TK_FLOAT_KW: return "'float'";
  case TK_FOR: return "'for'";
  case TK_GOTO: return "'goto'";
  case TK_IF: return "'if'";
  case TK_INLINE: return "'inline'";
  case TK_INT_KW: return "'int'";
  case TK_LONG: return "'long'";
  case TK_REGISTER: return "'register'";
  case TK_RESTRICT: return "'restrict'";
  case TK_RETURN: return "'return'";
  case TK_SHORT: return "'short'";
  case TK_SIGNED: return "'signed'";
  case TK_SIZEOF: return "'sizeof'";
  case TK_STATIC: return "'static'";
  case TK_STRUCT: return "'struct'";
  case TK_SWITCH: return "'switch'";
  case TK_TYPEDEF: return "'typedef'";
  case TK_UNION: return "'union'";
  case TK_UNSIGNED: return "'unsigned'";
  case TK_VOID: return "'void'";
  case TK_VOLATILE: return "'volatile'";
  case TK_WHILE: return "'while'";
  case TK_BOOL: return "'_Bool'";
  case TK_COMPLEX: return "'_Complex'";
  case TK_INT128: return "'__int128'";
  }
  return "token";
}
